// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwU11I70ywriR1jUHKgwSAP3umCT_cB6w',
    appId: '1:143738281173:web:1ae769c69a839f93a9565c',
    messagingSenderId: '143738281173',
    projectId: 'random-app-b4854',
    authDomain: 'random-app-b4854.firebaseapp.com',
    storageBucket: 'random-app-b4854.appspot.com',
    measurementId: 'G-M87H9SW2EP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClwrimoy-tzgZVSbBoUCpxKWns6YtiXvs',
    appId: '1:143738281173:android:42dd779a196c12f0a9565c',
    messagingSenderId: '143738281173',
    projectId: 'random-app-b4854',
    storageBucket: 'random-app-b4854.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD55msJvxjaKbieFQwX2uZ6FDRpc6xP8tc',
    appId: '1:143738281173:ios:8e0c81e098a0e077a9565c',
    messagingSenderId: '143738281173',
    projectId: 'random-app-b4854',
    storageBucket: 'random-app-b4854.appspot.com',
    iosClientId: '143738281173-17vkum0ra5p3oi46cm3d5rcmpv99c6mu.apps.googleusercontent.com',
    iosBundleId: 'com.example.random',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD55msJvxjaKbieFQwX2uZ6FDRpc6xP8tc',
    appId: '1:143738281173:ios:8e0c81e098a0e077a9565c',
    messagingSenderId: '143738281173',
    projectId: 'random-app-b4854',
    storageBucket: 'random-app-b4854.appspot.com',
    iosClientId: '143738281173-17vkum0ra5p3oi46cm3d5rcmpv99c6mu.apps.googleusercontent.com',
    iosBundleId: 'com.example.random',
  );
}
